name: Dev Docker Cache

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  docker-cache:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - name: debian12-i386
            context: ./docker-images/debian12-i386
            dockerfile: ./docker-images/debian12-i386/Dockerfile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ${{ matrix.image.name }} with cache
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.image.context }}
          file: ${{ matrix.image.dockerfile }}
          push: false
          load: false
          tags: amxmodx-discord-api/${{ matrix.image.name }}:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max