name: Dev Docker Cache

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  docker-cache:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - name: debian12-i386
            context: ./docker-images/debian12-i386
            dockerfile: ./docker-images/debian12-i386/Dockerfile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Create hash of Docker build context
      - name: Compute Docker context hash
        id: hash
        run: |
          HASH=$(find "${{ matrix.image.context }}" -type f -print0 \
            | sort -z \
            | xargs -0 sha256sum \
            | sha256sum \
            | awk '{print $1}')

          echo "hash=$HASH" >> $GITHUB_OUTPUT

      # Restore cache using that hash
      - name: Restore Docker build marker
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: .docker-cache-marker
          key: docker-${{ matrix.image.name }}-${{ steps.hash.outputs.hash }}

      # Build only if cache miss
      - name: Set up Docker Buildx
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build ${{ matrix.image.name }}
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.image.context }}
          file: ${{ matrix.image.dockerfile }}
          push: false
          load: false
          tags: amxmodx-discord-api/${{ matrix.image.name }}:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Save marker only for this hash
      - name: Create cache marker
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p .docker-cache-marker
          echo "built:${{ steps.hash.outputs.hash }}" > .docker-cache-marker/${{ matrix.image.name }}

      - name: Save cache marker
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: .docker-cache-marker
          key: docker-${{ matrix.image.name }}-${{ steps.hash.outputs.hash }}